### ISSUE TITLE
opencv_contrib functionality not working anymore

### ISSUE THREAD

**Issue by thomasbielagk** [shimat/opencvsharp#180]
In Version 3 in include_opencv.h you added #undef ENABLED_CONTRIB, resulting all opencv contrib methods not working anymore (e.g. face detection, BackgroundMOG). What is the reason to disable it?

**Comment by shimat** [comment]
The OpenCvSharp NuGet package bundles the opencv_world310.dll from the OpenCV official package. It does not contain contrib features, so OpenCvSharp's contrib wrapper is disabled at the moment. :persevere:

I want to eventually provide a custom opencv_world DLL and implement contrib wrapper. :muscle:

**Comment by fdncred** [comment]
I was able to compile all the contrib files however contrib_world.dll will not compile according to the opencv bug report I filed.  If they ever get this fixed it would be perfect to have both the world dlls.  I just can't figure out how to make cmake work to compile into contrib_world.dll.

**Comment by thomasbielagk** [comment]
Thanks guys, understood. So I guess I'll go with making a custom build for now to get those features back (module_face is a must).

@shimat Sounds cool. Let me know if I can help. Having a common solution would be nice.

@fdncred Saw your bug report. Also looked into the corresponding CMake files, turns out contrib_world apparently has been intentionally removed in 3.1, so my guess would be it won't come back.

**Comment by fdncred** [comment]
@thomasbielagk If you get the custom build working I'd like to see it if possible.  I'd love to have a contrib_world too!

**Comment by thomasbielagk** [comment]
Got it working.

First I built opencv + opencv_contrib.

cmake -DOPENCV_EXTRA_MODULES_PATH=..\..\opencv_contrib\modules\ ..
MSBuild OpenCV.sln /p:Configuration=Release
MSBuild INSTALL.vcxproj /p:Configuration=Release

Then go to OpenCvSharp:
In the project OpenCvSharpExtern, replace the preset directories for INCLUDE / LIBS
(bot point to a prebuild opencv) with the directories where you just built opencv, something like
<opencv-dir>\build\install\include
<opencv-dir>\build\install\x86\vc14\lib

In "include_opencv.h" remove the lines

#define ENABLED_CONTRIB
#undef ENABLED_CONTRIB

Finally add a preprocessor definition ENABLED_CONTRIB

Compiling this (Release mode), still gave me errors in face.h (face_createXXXRecognizer).
Replace the clone(...) calls with clone<FaceRecognizer>(...).

Now it should compile fine.
Using the new OpenCvSharpExtern.dll together with the required OpenCV dlls
(<opencv-dir>\build\install\x86\vc14\bin) should do fine, I can now run e.g.BackgroundSubtractorMOG.

Let me know if that works for you, If required I can also create and share a fork of the repo.

**Comment by fdncred** [comment]
@thomasbielagk Are you creating a contrib_world.dll or are you just using the opencv_world.dll with all the contrib modules compiled in?  If opencv_world, what is the size of your dll?  I've been down this path before but i got stuck with OpenCvSharpExtern not loading.

**Comment by thomasbielagk** [comment]
I am not creating a world DLL at all. As you said opencv now only includes few of the extension modules into world, so I decided to go with single DLLs (don't want to change opencv makefiles)

Building opencv via "cmake -DOPENCV_EXTRA_MODULES_PATH=....\opencv_contrib\modules\ .."
I get a bunch of DLLs (opencv\build\install\x86\vc14\bin):

 467k opencv_aruco310.dll
 156k opencv_bgsegm310.dll
 230k opencv_bioinspired310.dll
 1.3M opencv_calib3d310.dll
 603k opencv_ccalib310.dll
 8.6M opencv_core310.dll
 523k opencv_datasets310.dll
 1.6M opencv_dnn310.dll
 198k opencv_dpm310.dll
 244k opencv_face310.dll
 677k opencv_features2d310.dll
  12M opencv_ffmpeg310.dll
 421k opencv_flann310.dll
 138k opencv_fuzzy310.dll
 139k opencv_highgui310.dll
 2.2M opencv_imgcodecs310.dll
  20M opencv_imgproc310.dll
 327k opencv_line_descriptor310.dll
 587k opencv_ml310.dll
 535k opencv_objdetect310.dll
 246k opencv_optflow310.dll
 781k opencv_photo310.dll
 130k opencv_plot310.dll
 190k opencv_reg310.dll
 596k opencv_rgbd310.dll
 256k opencv_saliency310.dll
 271k opencv_shape310.dll
 268k opencv_stereo310.dll
 869k opencv_stitching310.dll
 121k opencv_structured_light310.dll
 256k opencv_superres310.dll
 372k opencv_surface_matching310.dll
 513k opencv_text310.dll
 3.2M opencv_tracking310.dll
 399k opencv_video310.dll
 221k opencv_videoio310.dll
 556k opencv_videostab310.dll
 589k opencv_xfeatures2d310.dll
 916k opencv_ximgproc310.dll
 207k opencv_xobjdetect310.dll
 498k opencv_xphoto310.dll

The size of those combined is ~60MB in release mode, so you getting a 400MB DLL sounds like too much.

Sorry about the confusing clone-line, didn't realize I had to escape the template so it doesn't look like an HTML tag :smiley: 
What I meant is
`clone(...)`
to
`clone<FaceRecognizer>(...)`

This way the method signature remains unchanged, but your way may work as well.

**Comment by fdncred** [comment]
@thomasbielagk Did you change OpenCvSharp to load these DLLs instead of loading opencv_world.dll?
NativeMethods.cs only wants to load one opencv dll.
```c#
private static readonly string[] OpenCVDllNames =
{
    "opencv_world",
};
```
I would like to see your code for OpenCvSharpExtern (and perhaps others) if it's not too much trouble. I can't get mine to load but that could be because I'm trying to load opencv_world as displayed above.

**Comment by thomasbielagk** [comment]
Created a fork:
https://github.com/thomasbielagk/opencvsharp

Visual Studio 2015, build OpenCvSharpExtern (Release, x86).
Good point about the loading, I assumed the DLLs would be loaded automagically (which appears to be the case, as I can see it working).

**Comment by fdncred** [comment]
@thomasbielagk Ok.  I see what you're doing.  You're just linking all the individual libs when you create the OpenCvSharpExtern.dll.  That is how they are auto-magically loading.

The only problem with that route is that the collateral DLLs need to be in the path where the exe can find them. Usually that means the same directory.

If they were in the referenced in the NativeMethods class then you could keep the collateral DLLs in the dll\x64 dll\x86 folders and the exe could find them.

Another problem that perhaps @shimat can help with is that since most of the contrib functions are not used anymore things like SURF just blow up because they haven't been tested.  Some things may work just find while others need implementation modifications.

Thanks @thomasbielagk for showing one method of getting some of the contrib functions working in OpenCvSharp!

**Comment by VahidN** [comment]
@shimat
Any updates about this issue?

**Comment by shimat** [comment]
I'm sorry for the late reply :bow: 
I released OpenCvSharpExtern.dll that is built with opencv_contrib static library. 🎉

**Comment by kishimoto-exvision** [comment]
FaceRecognizer.Create*FaceRecognizer does not seem to work on OpenCvSharp3-AnyCPU v 3.2.0.20170110.  EntryPointNotFoundException still happens.

**Comment by kishimoto-exvision** [comment]
(I think I should write this comment on the other thread, but I wrote here.)
I could not find any documents about compiling the latest source code, which are based on .NET Core (.xproj) and cmake.

And the build system will change again.
".NET Core Tools Switch to MSBuild"
https://www.infoq.com/news/2016/11/netcore-tools-msbuild
https://www.infoq.com/jp/news/2016/12/netcore-tools-msbuild

Comments in this thread contain various important view points related to the ground design of OpenCvSharp, I think.
Thank you for your consideration.

**Comment by shimat** [comment]
(日本語で失礼します)
有益な情報をありがとうございます。記事の通りdotnet migrateしてみましたら、うまくいったようですがVisual Studio 2015では読み込めないようです。2017RC移行ですね。

もし2015でビルドされるなら、こちらをお試しください。
https://www.microsoft.com/net/core#windowsvs2015

**Comment by kishimoto-exvision** [comment]
ご紹介頂いた内容試してみます。
早速のご返事どうもありがとうございました。
取り急ぎ御礼まで。

**Comment by thomasbielagk** [comment]
@matstumpf Haven't tried to compile to Xamarin Android. Will look at it at home. But you don't need my fork or custom code anymore, shimat has brought back support for the external stuff (using static lib). Just clone the repo.

Is Xamarin a fix requirement? I guess Java-Bindings might be easier to work with, like these: https://github.com/bytedeco/javacpp-presets
